spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop?useUnicode=true&characterEncoding=UTF-8&?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qweasdzxc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wiseblue.bean