spring:
  profiles:
    active:
      - dubbo
  dubbo:
    application:
      name: provider
    base-package: com.wiseblue.service
    registry:
        protocol: zookeeper
        address: 123.206.19.39:2181
    protocol:
      name: dubbo
      port: 20880
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop?useUnicode=true&characterEncoding=UTF-8&?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qweasdzxc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wiseblue.bean
server:
  port: 8080
